# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{epitools}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["epitron"]
  s.date = %q{2010-05-15}
  s.description = %q{Miscellaneous utility libraries to make my life easier.}
  s.email = %q{chris@ill-logic.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "epitools.gemspec",
     "lib/epitools.rb",
     "lib/epitools/basetypes.rb",
     "lib/epitools/hexdump.rb",
     "lib/epitools/http.rb",
     "lib/epitools/lcs.rb",
     "lib/epitools/metaclass.rb",
     "lib/epitools/niceprint.rb",
     "lib/epitools/permutations.rb",
     "lib/epitools/pretty_backtrace.rb",
     "lib/epitools/rails.rb",
     "lib/epitools/rash.rb",
     "lib/epitools/string_to_proc.rb",
     "spec/basetypes_spec.rb",
     "spec/lcs_spec.rb",
     "spec/metaclass_spec.rb",
     "spec/permutations_spec.rb",
     "spec/rash_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/epitron/epitools}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{NOT UTILS... METILS!}
  s.test_files = [
    "spec/permutations_spec.rb",
     "spec/rash_spec.rb",
     "spec/spec_helper.rb",
     "spec/lcs_spec.rb",
     "spec/basetypes_spec.rb",
     "spec/metaclass_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

